/**
 * Deployed Soroban contract IDs for Baraza's v2 five-contract workspace
 * (`contracts/stellar/`), per network.
 *
 * Source of truth: `contracts/stellar/addresses/testnet.json` (testnet) /
 * `contracts/stellar/addresses/mainnet.json` (mainnet, once deployed),
 * generated by `contracts/stellar/scripts/deploy.sh`. Per
 * `docs/decisions/CDR-0001.md`, the unversioned `addresses/<network>.json`
 * name belongs to this current five-contract v2 lineage; the deprecated v1
 * deployment keeps its own historical record in `addresses/testnet-v1.json`
 * and must never be merged into these.
 *
 * The testnet values below are the real IDs from the 2026-07-27 v2 testnet
 * deploy, inlined as defaults so the wiring is live without per-environment
 * configuration (same convention as `evmAddresses.ts`). The `VITE_STELLAR_*`
 * env vars stay as an override for pointing a build at a different
 * deployment without a code change.
 *
 * NOT_DEPLOYED (empty string) means Baraza has not deployed this contract to
 * that network yet — mainnet is entirely undeployed. Callers must check via
 * `isStellarContractDeployed` and fall back to off-chain-only behavior;
 * never attempt a contract call against the sentinel.
 *
 * CAVEAT — `treasury_vault` is DEPLOYED BUT NOT INITIALIZED. The v2 deploy
 * initialized 4 of 5 contracts and deliberately left the vault uninitialized
 * pending per-community parameters (see `contracts/stellar/scripts/`'s own
 * initialize guidance). Its ID is recorded here for completeness, but nothing
 * in `stellarClient.ts` calls it today, and nothing should until it is
 * initialized — a call against an uninitialized vault will fail at runtime.
 */

export const NOT_DEPLOYED = '';

/**
 * From `contracts/stellar/addresses/testnet.json` (deployedAt 2026-07-27T12:41:30Z).
 * Keep in sync with that file — it is what `deploy.sh` writes.
 */
const TESTNET_DEPLOYED = {
  communityRegistry: 'CADCWYITOQ5NECVVXM7F2ZXFHV42KXHPQQJGFYJGEA3OMJIRIOXDKWTV',
  governance: 'CAKAH5E6AEUDVSGGZTPUJ62YZDCMTTN4NYCFE2SXF3XQH75NR5VGRC4C',
  membership: 'CBX4Y2XPZ4KEXUDCPXQUYAKYLX257SG25ZKHWA6PMLJ5YC4IYFK4TLKT',
  paymentAttestation: 'CATOKZ2GC6A2H6TDXJP7MQVWHEJGLUWWE2LQ6OGWYROS6RL5TRRROUVZ',
  // Deployed, NOT initialized — see CAVEAT above.
  treasuryVault: 'CB6H4GYWSAPA6KBOSZWUNN5QAXKIQAW2TLL3QXTNOPAVPBDYPW5Y6767',
} as const;

export interface StellarContractAddresses {
  communityRegistry: string;
  governance: string;
  membership: string;
  paymentAttestation: string;
  treasuryVault: string;
}

const TESTNET: StellarContractAddresses = {
  communityRegistry: import.meta.env.VITE_STELLAR_COMMUNITY_REGISTRY_ID?.trim() || TESTNET_DEPLOYED.communityRegistry,
  governance: import.meta.env.VITE_STELLAR_GOVERNANCE_ID?.trim() || TESTNET_DEPLOYED.governance,
  membership: import.meta.env.VITE_STELLAR_MEMBERSHIP_ID?.trim() || TESTNET_DEPLOYED.membership,
  paymentAttestation: import.meta.env.VITE_STELLAR_PAYMENT_ATTESTATION_ID?.trim() || TESTNET_DEPLOYED.paymentAttestation,
  treasuryVault: import.meta.env.VITE_STELLAR_TREASURY_VAULT_ID?.trim() || TESTNET_DEPLOYED.treasuryVault,
};

const MAINNET: StellarContractAddresses = {
  communityRegistry: NOT_DEPLOYED,
  governance: NOT_DEPLOYED,
  membership: NOT_DEPLOYED,
  paymentAttestation: NOT_DEPLOYED,
  treasuryVault: NOT_DEPLOYED,
};

export function getStellarContractAddresses(network: 'testnet' | 'mainnet'): StellarContractAddresses {
  return network === 'mainnet' ? MAINNET : TESTNET;
}

export function isStellarContractDeployed(contractId: string): boolean {
  return contractId.length > 0;
}
