/**
 * Deployed Soroban contract IDs for Baraza's v2 five-contract workspace
 * (`contracts/stellar/`), per network.
 *
 * Source: contracts/stellar/addresses/testnet-v2.json (testnet) /
 * contracts/stellar/addresses/mainnet.json (mainnet, once deployed).
 * Generated by `contracts/stellar/scripts/deploy.sh` — see
 * `docs/decisions/CDR-0001.md` for why this is `-v2` and not the plain
 * `testnet.json` the script writes by default (that name is reserved for
 * the deprecated `testnet-v1.json` lineage's own historical record).
 *
 * NOT_DEPLOYED means Baraza has not deployed this contract to that network
 * yet. Callers must check for this sentinel and fall back to off-chain-only
 * behavior (mirrors `evmAddresses.ts`'s NOT_DEPLOYED convention) — never
 * attempt a contract call against it.
 *
 * When the v2 testnet deployment lands, replace the testnet entries below
 * with the real contract IDs from `contracts/stellar/addresses/testnet-v2.json`.
 */

export const NOT_DEPLOYED = '';

export interface StellarContractAddresses {
  communityRegistry: string;
  governance: string;
  membership: string;
  paymentAttestation: string;
  treasuryVault: string;
}

const TESTNET: StellarContractAddresses = {
  communityRegistry: import.meta.env.VITE_STELLAR_COMMUNITY_REGISTRY_ID?.trim() || NOT_DEPLOYED,
  governance: import.meta.env.VITE_STELLAR_GOVERNANCE_ID?.trim() || NOT_DEPLOYED,
  membership: import.meta.env.VITE_STELLAR_MEMBERSHIP_ID?.trim() || NOT_DEPLOYED,
  paymentAttestation: import.meta.env.VITE_STELLAR_PAYMENT_ATTESTATION_ID?.trim() || NOT_DEPLOYED,
  treasuryVault: import.meta.env.VITE_STELLAR_TREASURY_VAULT_ID?.trim() || NOT_DEPLOYED,
};

const MAINNET: StellarContractAddresses = {
  communityRegistry: NOT_DEPLOYED,
  governance: NOT_DEPLOYED,
  membership: NOT_DEPLOYED,
  paymentAttestation: NOT_DEPLOYED,
  treasuryVault: NOT_DEPLOYED,
};

export function getStellarContractAddresses(network: 'testnet' | 'mainnet'): StellarContractAddresses {
  return network === 'mainnet' ? MAINNET : TESTNET;
}

export function isStellarContractDeployed(contractId: string): boolean {
  return contractId.length > 0;
}
